# Generated by Django 3.2.9 on 2021-11-10 10:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_datetime', models.DateTimeField()),
                ('event_vibes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('host_email', models.EmailField(max_length=50)),
                ('host_first_name', models.CharField(max_length=50)),
                ('host_last_name', models.CharField(max_length=50)),
                ('num_attendees', models.IntegerField()),
                ('game_type', models.CharField(choices=[('VAL', 'Valorant'), ('LOL', 'League'), ('CSG', 'CSGO'), ('DOT', 'Dota'), ('PUB', 'PUBG'), ('SMA', 'Smash')], max_length=3)),
            ],
        ),
    ]
