# Generated by Django 3.2.9 on 2021-11-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
