# Generated by Django 3.2.9 on 2021-11-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_userevent_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
