# Generated by Django 3.2.9 on 2021-11-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_userevent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userevent',
            constraint=models.UniqueConstraint(fields=('email_address', 'event_id'), name='users can attend an event at most once'),
        ),
    ]
