# Generated by Django 3.1.2 on 2021-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
